# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Github Actions Maven Build

on:
  release:
    types: [ created ]
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Step 1 - Checkout branch
        uses: actions/checkout@v4

      - name: Step 2 - Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Step 3 - Build with Maven
        run: mvn -B package --file pom.xml

      - name: Step 4 - Extract pom version
        id: extract_version
        run: version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)

      - name: Step 5 - Set version for deploy
        run: mvn versions:set "-DnewVersion=${{ steps.extract_version.outputs.version }}"

      - name: Step 6 - Publish to GitHub Packages Apache Maven
        run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
        env:
          GITHUB_TOKEN: ${{ github.token }}